#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is the main executable for the application.
# Este arquivo é o executável principal para a aplicação.

# Copyright (c) 2025, Lumiert
# Licensed under the MIT License.
# See LICENSE file for details.

from notification import show_notification

# Exemplo de uso
title = "🔔 Novo Classificado!"
message = "CDJ 2000.\n\nA 2km de você"
link = "https://google.com"

show_notification(title, message, link)